# INTERVAL_OPTIONS
BROADCAST_INTERVAL = 2
LISTEN_INTERVAL = BROADCAST_INTERVAL * 2

# NETWORK_OPTIONS
BROADCAST_PORT = 50000
SUBNETMASK = "255.255.255.0"

# MESSAGE_OPTIONS
MESSAGE_PREFIX = "FILEDROP::"

PRESENCE_MESSAGE = MESSAGE_PREFIX + "HELLO"

SHARE_PERMISSION = MESSAGE_PREFIX + "SHARE"